---
title: Patrickirvin Io Netlify
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Late Night Dev
description: patrickirvin.io Developer Blog
site_description: Welcome to patrickirvin.io. My blog features highlights I encounter in my daily work as a Solution Architect, some interesting projects I work on outside of my career, some photography, some flying, and lots of outdoors.
logo: 
favicon: assets/images/favicon.ico
baseurl: 
production_url: https://patrickirvin.io/
disqus: justgoodthemes
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
ga_analytics: 
email: patrick@patrickirvin.io
contact_page_description: Please submits comments and questions using the form below.
thankyou_page_description: Your message has been successfully sent. We will contact
  you very soon!
sidebar_widget_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Donec sed lacus id tortor iaculis iaculis dignissim eget justo. Maecenas posuere
  eros nisl, ut pharetra turpis faucibus.
sidebar_widget_email: blogin [at] gmail.com
sidebar_widget_address: 123 Some Street, Some City, AA 12345
sidebar_widget_phone: "+123 112 23445"
twitter: JustGoodThemes
facebook: username
github: patrickirvinio
codepen: username
dribbble: username
medium: "@username"
instagram: username
pinterest: username
linkedin: admin@pcient.com
navigation:
- text: About
  url: "/about/"
- text: Style Guide
  url: "/style-guide/"
- text: Contact Me
  url: "/contact/"
plugins_dir:
- jekyll-author-page
- jekyll-paginate
- jekyll-tagsgenerator
- jekyll-seo-tag
- jekyll-sitemap
- sidenote
paginate: 6
paginate_path: "/page:num/"
permalink: "/:title"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
