---
title: Patrickirvin Io Netlify
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Curious
description: Bold Theme For Brave People
site_description: Welcome to my blog. It features topics such as fashion, architecture,
  travel & design. This blog is about finding balance in life, living with purpose,
  having fun, and doing what you love.
logo: 
favicon: assets/images/favicon.ico
baseurl: 
production_url: https://curious-jekyll.netlify.com/
disqus: justgoodthemes
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
ga_analytics: 
email: youremail@email.com
contact_page_description: Forma theme comes with a contact form built-in. You can
  use this form with Formspree service and get up to 50 submissions for free. Also,
  you can easily switch to another service if you want.
thankyou_page_description: Your message has been successfully sent. We will contact
  you very soon!
sidebar_widget_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Donec sed lacus id tortor iaculis iaculis dignissim eget justo. Maecenas posuere
  eros nisl, ut pharetra turpis faucibus.
sidebar_widget_email: blogin [at] gmail.com
sidebar_widget_address: 123 Some Street, Some City, AA 12345
sidebar_widget_phone: "+123 112 23445"
twitter: JustGoodThemes
facebook: username
github: JustGoodThemes
codepen: username
dribbble: username
medium: "@username"
instagram: username
pinterest: username
linkedin: username
navigation:
- text: About
  url: "/about/"
- text: Style Guide
  url: "/style-guide/"
- text: Contact Me
  url: "/contact/"
plugins_dir:
- jekyll-author-page
- jekyll-paginate
- jekyll-tagsgenerator
- jekyll-seo-tag
- jekyll-sitemap
- sidenote
paginate: 6
paginate_path: "/page:num/"
permalink: "/:title"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
